# Fantasy Football Roast Agent Configuration - EXAMPLE FILE
# =============================================================================
# 🔥 DO NOT EDIT THIS FILE DIRECTLY 🔥
# =============================================================================
# 
# For LOCAL CLI usage:
#   1. Copy this file: cp config.py config.local.py
#   2. Edit config.local.py with your actual league ID and username
#   3. config.local.py is gitignored and won't be committed
#
# For WEB APP (Streamlit):
#   - No config needed! Just enter values in the web interface
# 
# This example config.py is safe to commit to GitHub
# =============================================================================

# League Information
LEAGUE_ID = "123456789012345678"   # Your Sleeper league ID (find in your league URL)
SEASON = "2025"                    # Current season year

# Target Configuration  
TARGET_DISPLAY_NAME = "username"   # Display name of user to roast

# AWS Configuration (for CLI with Bedrock - optional)
AWS_REGION = "us-west-2"           # AWS region for Bedrock
MODEL_ID = "us.anthropic.claude-3-7-sonnet-20250219-v1:0"  # Bedrock model

# API Configuration
SLEEPER_API_BASE = "https://api.sleeper.app/v1"
RATE_LIMIT_DELAY = 0.1  # Delay between API calls (seconds)

# Output Configuration
OUTPUT_DIR = "reports"             # Directory to save HTML reports
REPORT_FILENAME_FORMAT = "roast_{display_name}_{timestamp}.html"

# Report Settings
MAX_WAIVER_TARGETS = 5            # Number of waiver wire recommendations
MAX_TRADE_SUGGESTIONS = 3         # Number of trade suggestions
WEB_SEARCH_RESULTS = 5           # Number of web search results per query

# =============================================================================
# CONSTANTS (Don't change these unless you know what you're doing)
# =============================================================================

# Sleeper API endpoints
ENDPOINTS = {
    "nfl_state": f"{SLEEPER_API_BASE}/state/nfl",
    "user": f"{SLEEPER_API_BASE}/user/{{identifier}}",
    "league": f"{SLEEPER_API_BASE}/league/{{league_id}}",
    "league_users": f"{SLEEPER_API_BASE}/league/{{league_id}}/users", 
    "league_rosters": f"{SLEEPER_API_BASE}/league/{{league_id}}/rosters",
    "league_matchups": f"{SLEEPER_API_BASE}/league/{{league_id}}/matchups/{{week}}",
    "players": f"{SLEEPER_API_BASE}/players/nfl",
    "trending_adds": f"{SLEEPER_API_BASE}/players/nfl/trending/add",
    "trending_drops": f"{SLEEPER_API_BASE}/players/nfl/trending/drop",
    "draft": f"{SLEEPER_API_BASE}/draft/{{draft_id}}",
    "draft_picks": f"{SLEEPER_API_BASE}/draft/{{draft_id}}/picks"
}

# Position mappings for analysis
POSITION_GROUPS = {
    "QB": ["QB"],
    "RB": ["RB"],
    "WR": ["WR"], 
    "TE": ["TE"],
    "FLEX": ["RB", "WR", "TE"],
    "K": ["K"],
    "DEF": ["DEF"]
}

# Scoring weights for player value analysis (PPR)
PPR_WEIGHTS = {
    "passing_yards": 0.04,
    "passing_tds": 4.0,
    "passing_ints": -2.0,
    "rushing_yards": 0.1,
    "rushing_tds": 6.0,
    "receiving_yards": 0.1,
    "receiving_tds": 6.0,
    "receptions": 1.0,  # PPR bonus
    "fumbles_lost": -2.0
}

def get_config():
    """Return configuration dictionary
    
    Note: For local development, create config.local.py with your actual values.
    This will use config.local.py if it exists, otherwise falls back to these defaults.
    """
    # Try to import from config_local.py first (gitignored, for local dev)
    # Import as module to avoid conflicts
    import importlib.util
    import os
    
    config_local_path = os.path.join(os.path.dirname(__file__), 'config.local.py')
    
    if os.path.exists(config_local_path):
        # Load config.local.py
        spec = importlib.util.spec_from_file_location("config_local", config_local_path)
        config_local = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(config_local)
        league_id = config_local.LEAGUE_ID
        target_name = config_local.TARGET_DISPLAY_NAME
    else:
        # Use defaults from this file
        league_id = LEAGUE_ID
        target_name = TARGET_DISPLAY_NAME
    
    return {
        "league_id": league_id,
        "season": SEASON,
        "target_display_name": target_name,
        "aws_region": AWS_REGION,
        "model_id": MODEL_ID,
        "sleeper_api_base": SLEEPER_API_BASE,
        "rate_limit_delay": RATE_LIMIT_DELAY,
        "output_dir": OUTPUT_DIR,
        "report_filename_format": REPORT_FILENAME_FORMAT,
        "max_waiver_targets": MAX_WAIVER_TARGETS,
        "max_trade_suggestions": MAX_TRADE_SUGGESTIONS,
        "web_search_results": WEB_SEARCH_RESULTS,
        "endpoints": ENDPOINTS,
        "position_groups": POSITION_GROUPS,
        "ppr_weights": PPR_WEIGHTS
    }

def create_runtime_config(
    league_id: str,
    target_name: str,
    api_key: str,
    provider: str = "anthropic",
    model: str = None,
    season: str = "2025"
):
    """
    Create configuration at runtime from user inputs (for Streamlit app)
    
    Args:
        league_id: Sleeper league ID
        target_name: Display name of user to roast
        api_key: Anthropic or OpenAI API key
        provider: "anthropic" or "openai"
        model: Optional model override (auto-selected if None)
        season: Season year (defaults to 2025)
    
    Returns:
        Configuration dictionary
    """
    # Auto-select model based on provider
    if model is None:
        model = "claude-3-7-sonnet-20250219" if provider == "anthropic" else "gpt-4o"
    
    # Start with base config
    base_config = get_config()
    
    # Override with runtime values
    base_config.update({
        "league_id": league_id,
        "target_display_name": target_name,
        "api_provider": provider,
        "api_key": api_key,
        "model_id": model,
        "season": season,
    })
    
    return base_config 